name: Run Karate Tests

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run Karate tests
        run: |
          chmod +x ./gradlew
          ./gradlew clean test -Dkarate.env=ci

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests
